package com.itheima.pojo;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.time.LocalDateTime;

/**
 * Represents a log entry for department-related actions within the application.
 * This class is used to store information about various events or actions that affect departments,
 * such as creation, modification, or deletion of department records.
 */
@Data
@NoArgsConstructor
@AllArgsConstructor
public class DeptLog {
    /**
     * Unique identifier for the department log entry.
     * This is typically generated by the database upon insertion.
     */
    private Integer id;

    /**
     * The date and time when the log entry was created.
     * This captures the exact moment when the related department action occurred.
     */
    private LocalDateTime createTime;

    /**
     * A description of the action or event that the log entry records.
     * This should provide enough detail to understand what change or event took place.
     */
    private String description;
}
